version: "3.8"

services:
  app:
    image: event_app_chat_service:latest
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: node server.js
    ports:
      - ${APP_HOST}:${APP_PORT}:3030

  db:
    image: mongo:5
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    ports:
      - ${DB_PORT}:27017

volumes:
  mongodb_data:

